[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pulsedeploy"
version = "0.0.1"
description = "PulseDeploy application"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["pulsedeploy"]
