name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read       # needed for checkout
  packages: write      # needed to push Docker images

env:
  IMAGE_NAME: ghcr.io/adetunji0602/pulsedeploy
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ------------------ TERRAFORM INFRA ------------------
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: Terraform Init
      working-directory: terraform/aks
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform/aks
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: terraform/aks
      run: terraform apply -auto-approve tfplan

    # ------------------ EXTRACT AKS INFO ------------------
    - name: Get AKS output from Terraform
      working-directory: terraform/aks
      shell: bash
      run: |
        echo "RESOURCE_GROUP=$(terraform output -raw resource_group)" >> $GITHUB_ENV
        echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV

    # ------------------ PYTHON BUILD & TEST ------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -e .

    - name: Run tests
      run: pytest

    # ------------------ DOCKER & GHCR ------------------
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: adetunji0602
        password: ${{ secrets.PULSEDEPLOY }}

    - name: Build and push image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile .
        docker push $IMAGE_NAME:$IMAGE_TAG

    # ------------------ KUBERNETES DEPLOY ------------------
    - name: Get AKS credentials from Terraform output
      run: |
        az aks get-credentials \
          --resource-group $RESOURCE_GROUP \
          --name $CLUSTER_NAME \
          --overwrite-existing

    - name: Deploy with Helm
      run: |
        helm upgrade --install pulsedeploy helm/pulsedeploy \
          --namespace pulsedeploy \
          --create-namespace \
          --set image.repository=$IMAGE_NAME \
          --set image.tag=$IMAGE_TAG
