name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

permissions:
  contents: read       # needed for checkout
  packages: write      # needed to push Docker images

env:
  IMAGE_NAME: ghcr.io/adetunji0602/pulsedeploy
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ✅ 1. Set up Python (MUST come before pip / pytest)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # ✅ 2. Install dependencies + install your package
    - name: Install dependencies and package
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -e .

    # ✅ 3. Run tests ONCE
    - name: Run tests
      run: pytest

    # ------------------ DOCKER & DEPLOY ------------------

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: adetunji0602
        password: ${{ secrets.PULSEDEPLOY }}

    - name: Build and push image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile .
        docker docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Setup kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      env:
        KUBECONFIG: kubeconfig

    - name: Deploy with Helm
      run: |
        helm upgrade --install pulsedeploy helm/pulsedeploy \
          --namespace pulsedeploy \
          --create-namespace \
          --set image.repository=$IMAGE_NAME \
          --set image.tag=$IMAGE_TAG
